site_name: MediBridge Lifecycle Hub
site_url: https://bridgingknowledge.github.io/medibridge-lifecycle-hub/
repo_url: https://github.com/BridgingKnowledge/medibridge-lifecycle-hub
repo_name: GitHub
edit_uri: edit/main/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets

plugins:
  - search

# Hvis du har lagt en lille CSS (kan være tom i starten)
extra_css:
  - assets/extra.css

# Mermaid support via CDN + lille init-script der re-initialiserer på sideskift
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - assets/mermaid-init.js

nav:
  - Home: index.md
  - Welcome: 00-intro/welcome.md
  - 01 Business Case: 01-business-case/index.md
  - 02 Regulatory & Stakeholders: 02-regulatory-and-stakeholders/index.md
  - 03 Requirements & Design: 03-requirements-design/index.md
  - 04 Risk & QMS: 04-risk-qms/index.md
  - 05 Validation: 05-validation/index.md
  - 06 InfoSec & IAM: 06-infosec-iam/index.md
  - 07 Operations & Monitoring: 07-operations-monitoring/index.md
  - 08 Incidents & Deviations: 08-incidents-deviations/index.md
  - 09 Change Control: 09-change-control/index.md
  - 10 Roles & Responsibilities: 10-roles-responsibilities/index.md
  - 11 Supplier Management: 11-supplier-management/index.md
  - 12 Training & Competence: 12-training-competence/index.md
  - 13 Audit & Compliance: 13-audit-compliance/index.md
  - 14 BCP/DRP: 14-bcp-drp/index.md
  - 15 PMS & Complaints: 15-pms-complaints/index.md
  - 16 Continuous Improvement: 16-continuous-improvement/index.md
  - 17 Decommissioning: 17-decommissioning/index.md
  - Governance API: gov-api.md
